# Generated by Django 4.2.30 on 2026-04-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_detail_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergens',
            field=models.CharField(blank=True, default='', help_text='e.g. Contains nuts, dairy', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(blank=True, default='', help_text='e.g. 30 days at room temperature', max_length=60),
        ),
    ]
