# Generated by Django 4.2.30 on 2026-04-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_allergens_alter_product_shelf_life'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sweetener',
            field=models.CharField(choices=[('sugar', 'Sugar'), ('brown_sugar', 'Brown Sugar'), ('unsweetened', 'Unsweetened')], default='sugar', max_length=20),
        ),
    ]
