# Generated by Django 4.2.30 on 2026-04-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_add_sweetener_to_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
